name: Java CI

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create the JAR file with Maven
        run: mvn package -DskipTests

  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - name: Start application
        run: nohup mvn spring-boot:run > /dev/null 2>&1 &

      - name: Wait for 10 seconds
        run: sleep 10
        
        
        

