name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
        # create JAR file with maven and run the package
      - name: Create the JAR file with Maven
        run: mvn package -DskipTests
         
      - name: Start applicatie
        run: nohup mvn spring-boot:run > /dev/null 2>&1 &
      - name: Wait 10 seconds so the application is ready
        run: sleep 10
